### ISSUE TITLE
Fatal when teaser not defined

### ISSUE THREAD

**Issue by tamw-wnet** [OpenPublicMedia/npr-cds-wordpress#17]
Seeing an error

WordPress database error Column 'post_excerpt' cannot be null for query INSERT INTO `wp_posts` 

that comes after earlier
PHP Warning:  Undefined property: stdClass::$teaser in /wp-content/plugins/npr-cds-wordpress/classes/NPR_CDS_WP.php on line 243
and
PHP Warning:  Undefined property: stdClass::$teaser in /wp-content/plugins/npr-cds-wordpress/classes/NPR_CDS_WP.php on line 557

so I'm assuming that the issue is some stories don't have a teaser and a default isn't getting generated.

FYI @jwcounts

**Comment by jwcounts** [comment]
Do you have any sample IDs, or did it happen during a Get Multi query?

**Comment by tamw-wnet** [comment]
nx-s1-4983063 triggered it

I have a PR I'm about to send to fix.

**Comment by tamw-wnet** [comment]
looks fixed.
