### ISSUE TITLE
Enable Support for Custom Post Types in "Get NPR Stories" Page

### ISSUE THREAD

**Issue by kaymly** [OpenPublicMedia/npr-cds-wordpress#7]
The "Get NPR Stories" page to pull Stories is currently can be accessed through standard posts menu. This change provides users with the ability to integrate the feature with their existing custom post types, extending the plugin's functionality beyond the standard WordPress "post" type.

**Comment by jwcounts** [comment]
Removed the filter that was created, but updated the functions to pull in the `npr_cds_pull_post_type` option, which achieves the same goal
